In [1]:
import numpy as np
import pandas as pd

air = pd.read_csv('air-quality.csv').fillna(
    axis = 0, 
    method = 'ffill'
).drop(
    columns = ['Number of Trends Sites', 'CBSA']
).melt(
    id_vars = ['Core Based Statistical Area', 'Pollutant', 'Trend Statistic'],
    var_name = 'Year',
    value_name = 'Measurement'
).pivot_table(
    index = ['Core Based Statistical Area', 'Year'],
    columns = ['Pollutant', 'Trend Statistic'],
    values = 'Measurement'
).reset_index()

air['State'] = air['Core Based Statistical Area'].str.split(pat = ',', expand = True).loc[:, 1]
air['City'] = air['Core Based Statistical Area'].str.split(pat = ',', expand = True).loc[:, 0]

air.columns = air.columns.get_level_values(level = 0)

air_tidy = air.rename_axis(columns = '').drop(columns = 'Core Based Statistical Area')

air_tidy.to_csv('air.csv', index = False)

In [2]:
air_tidy.head()

   Year  CO  NO2  NO2  O3  PM10  PM2.5  PM2.5  Pb  SO2 State      City
0  2000 NaN  NaN  NaN NaN  50.0   23.0    8.6 NaN  NaN    SD  Aberdeen
1  2001 NaN  NaN  NaN NaN  58.0   23.0    8.6 NaN  NaN    SD  Aberdeen
2  2002 NaN  NaN  NaN NaN  59.0   20.0    7.9 NaN  NaN    SD  Aberdeen
3  2003 NaN  NaN  NaN NaN  66.0   21.0    8.4 NaN  NaN    SD  Aberdeen
4  2004 NaN  NaN  NaN NaN  39.0   23.0    8.1 NaN  NaN    SD  Aberdeen

In [4]:
us_state_abbrev = {
    'Alabama': 'AL',
    'Alaska': 'AK',
    'American Samoa': 'AS',
    'Arizona': 'AZ',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Delaware': 'DE',
    'District of Columbia': 'DC',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Guam': 'GU',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Northern Mariana Islands':'MP',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Pennsylvania': 'PA',
    'Puerto Rico': 'PR',
    'Rhode Island': 'RI',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virgin Islands': 'VI',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY'
}

# thank you to @kinghelix and @trevormarburger for this idea
abbrev_us_state = dict(map(reversed, us_state_abbrev.items()))

abbrev_us_state

{'AL': 'Alabama',
 'AK': 'Alaska',
 'AS': 'American Samoa',
 'AZ': 'Arizona',
 'AR': 'Arkansas',
 'CA': 'California',
 'CO': 'Colorado',
 'CT': 'Connecticut',
 'DE': 'Delaware',
 'DC': 'District of Columbia',
 'FL': 'Florida',
 'GA': 'Georgia',
 'GU': 'Guam',
 'HI': 'Hawaii',
 'ID': 'Idaho',
 'IL': 'Illinois',
 'IN': 'Indiana',
 'IA': 'Iowa',
 'KS': 'Kansas',
 'KY': 'Kentucky',
 'LA': 'Louisiana',
 'ME': 'Maine',
 'MD': 'Maryland',
 'MA': 'Massachusetts',
 'MI': 'Michigan',
 'MN': 'Minnesota',
 'MS': 'Mississippi',
 'MO': 'Missouri',
 'MT': 'Montana',
 'NE': 'Nebraska',
 'NV': 'Nevada',
 'NH': 'New Hampshire',
 'NJ': 'New Jersey',
 'NM': 'New Mexico',
 'NY': 'New York',
 'NC': 'North Carolina',
 'ND': 'North Dakota',
 'MP': 'Northern Mariana Islands',
 'OH': 'Ohio',
 'OK': 'Oklahoma',
 'OR': 'Oregon',
 'PA': 'Pennsylvania',
 'PR': 'Puerto Rico',
 'RI': 'Rhode Island',
 'SC': 'South Carolina',
 'SD': 'South Dakota',
 'TN': 'Tennessee',
 'TX': 'Texas',
 'UT': 'Utah',
 'VT': 'Vermont',
 'VI': 'Virgin Islands',
 'VA': 'Virginia',
 'WA': 'Washington',
 'WV': 'West Virginia',
 'WI': 'Wisconsin',
 'WY': 'Wyoming'}